In [4]:
'''
1. Numpy array x Python list

'''
 

import numpy as np

np.array([[1,2],['a', b'b']])

array([['1', '2'],
       ['a', 'b']], dtype='<U21')

In [9]:
# 2. Eficiencia Numpy
%time
soma = 0
for i in range(0, 1000000001):
    soma += i
print(soma)

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 13.1 µs
500000000500000000


In [10]:
# 2. Eficiencia Numpy
%time
np.arange(0, 1000000001).sum()

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 11 µs


500000000500000000

In [11]:
# 3. slicing
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a[1:2,1:]

array([[5, 6]])

In [14]:
data = np.loadtxt('../iris-dataset/iris.data.txt', delimiter=',', usecols=range(0,4))

In [67]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [53]:
mat = np.array([[1,3],[2,1]])
np.dot(mat, np.linalg.inv(mat))

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [55]:
np.array([[1,2],[1,2]])*np.array([[1, 3],[1,3]])

array([[1, 6],
       [1, 6]])

In [64]:
np.linalg.det(mat)

-5.000000000000001

In [26]:
a = np.array([[1+1j, 2+1j], [3+4j, 1+3j]])
ainv = np.linalg.inv(a)
print(ainv)

[[-0.38461538-0.07692308j  0.23076923-0.15384615j]
 [ 0.61538462-0.07692308j -0.16923077+0.04615385j]]


In [28]:
np.dot(a, ainv)

array([[ 1.00000000e+00-5.55111512e-17j, -5.55111512e-17-1.38777878e-17j],
       [-2.22044605e-16-2.22044605e-16j,  1.00000000e+00-5.55111512e-17j]])

In [7]:
m1 = np.matrix?
#np.linalg.inv(m1)

In [14]:
m1 = np.matrix('1 2; 3 4')
np.linalg.inv(m1) * m1

matrix([[1.00000000e+00, 0.00000000e+00],
        [2.22044605e-16, 1.00000000e+00]])

In [15]:
np.dot(np.linalg.inv(m1),m1)

matrix([[1.00000000e+00, 0.00000000e+00],
        [2.22044605e-16, 1.00000000e+00]])